# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_debug_wkb <- function(wkb) {
    invisible(.Call(`_wkutils_cpp_debug_wkb`, wkb))
}

cpp_debug_wkt <- function(input) {
    invisible(.Call(`_wkutils_cpp_debug_wkt`, input))
}

cpp_debug_wkt_streamer <- function(input) {
    invisible(.Call(`_wkutils_cpp_debug_wkt_streamer`, input))
}

cpp_debug_wksxp <- function(input) {
    invisible(.Call(`_wkutils_cpp_debug_wksxp`, input))
}

